
version: 2

sources:
  - name: lm_histo
    database: lemans2k26-project
    schema: lm_histo
    tables:
      - name: lm_22_raw
        identifier: lm_22
      - name: lm_23_raw
        identifier: lm_23        
      - name: lm_24_raw
        identifier: lm_24
      - name: lm_25_raw
        identifier: lm_25
